// ─────────────────────────────────────────────────────────────────
// TeeRadar – Seed script: alla 191 GolfManager-klubbar
// Kör med: node scripts/seed-clubs.js
// Kräver: SUPABASE_URL och SUPABASE_SERVICE_KEY i miljön (.env eller Railway)
// ─────────────────────────────────────────────────────────────────

import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY
);

export const ALL_CLUBS = [
  { slug: 'alhaurin-golf', name: 'Alhaurin Golf', area: 'Costa del Sol', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'aloha-golf-club', name: 'Aloha Golf Club', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'antequera-golf', name: 'Antequera Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'anoreta-golf', name: 'Añoreta Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'los-arqueros-golf', name: 'Los Arqueros Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'artola-golf', name: 'Artola Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'atalaya-old-course', name: 'Atalaya Old Course', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'atalaya-new-course', name: 'Atalaya New Course', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'baviera-golf', name: 'Baviera Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'benalmadena-golf', name: 'Benalmádena Golf', area: 'Costa del Sol', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'real-club-de-golf-las-brisas', name: 'Real Club de Golf Las Brisas', area: 'Costa del Sol', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'cabopino-golf', name: 'Cabopino Golf', area: 'Costa del Sol', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'la-cala-campo-america', name: 'La Cala Campo America', area: 'Costa del Sol', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'la-cala-campo-asia', name: 'La Cala Campo Asia', area: 'Costa del Sol', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'la-cala-campo-europa', name: 'La Cala Campo Europa', area: 'Costa del Sol', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'calanova-golf', name: 'Calanova Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'el-campanario', name: 'El Campanario', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'el-candado', name: 'El Candado', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'casares-golf', name: 'Casares Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'cerrado-del-aguila', name: 'Cerrado del Águila', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'el-chaparral', name: 'El Chaparral', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'coto-de-la-serena', name: 'Coto de la Serena', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'dama-de-noche', name: 'Dama de Noche', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'dona-julia-golf', name: 'Doña Julia Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'la-duquesa-golf', name: 'La Duquesa Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'estepona-golf', name: 'Estepona Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'finca-cortesin-golf', name: 'Finca Cortesin Golf', area: 'Costa del Sol', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'villa-padierna-flamingos', name: 'Villa Padierna Flamingos', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'villa-padierna-tramores', name: 'Villa Padierna Tramores', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'greenlife-golf', name: 'Greenlife Golf', area: 'Costa del Sol', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'real-club-de-golf-guadalmina-norte', name: 'Real Club de Golf Guadalmina Norte', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'real-club-de-golf-guadalmina-sur', name: 'Real Club de Golf Guadalmina Sur', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'guadalhorce-golf', name: 'Guadalhorce Golf', area: 'Costa del Sol', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'la-hacienda-links', name: 'La Hacienda Links', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'la-hacienda-heathland', name: 'La Hacienda Heathland', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'la-canada-golf', name: 'La Cañada Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'la-noria-golf', name: 'La Noria Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'la-quinta-golf', name: 'La Quinta Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'la-reserva-club-sotogrande', name: 'La Reserva Club Sotogrande', area: 'Costa del Sol', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'lauro-golf', name: 'Lauro Golf', area: 'Costa del Sol', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'los-naranjos-golf', name: 'Los Naranjos Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'marbella-golf-and-country-club', name: 'Marbella Golf & Country Club', area: 'Costa del Sol', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'mijas-golf-los-lagos', name: 'Mijas Golf Los Lagos', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'mijas-golf-los-olivos', name: 'Mijas Golf Los Olivos', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'monte-mayor-golf', name: 'Monte Mayor Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'parador-de-malaga-golf', name: 'Parador de Málaga Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'el-paraiso-golf', name: 'El Paraíso Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'rio-real-golf', name: 'Rio Real Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'san-roque-club-old-course', name: 'San Roque Club Old Course', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'san-roque-club-new-course', name: 'San Roque Club New Course', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'santa-clara-golf', name: 'Santa Clara Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'santa-maria-polo-and-golf', name: 'Santa María Polo & Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'santana-golf', name: 'Santana Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'el-soto-de-marbella', name: 'El Soto de Marbella', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'real-club-de-golf-sotogrande', name: 'Real Club de Golf Sotogrande', area: 'Costa del Sol', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'torrequebrada-golf', name: 'Torrequebrada Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'real-club-valderrama', name: 'Real Club Valderrama', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'valle-romano-golf', name: 'Valle Romano Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'villa-padierna-alferini', name: 'Villa Padierna Alferini', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'alcaidesa-links', name: 'Alcaidesa Links', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'alcaidesa-heathland', name: 'Alcaidesa Heathland', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'la-zagaleta-old-course', name: 'La Zagaleta Old Course', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'la-zagaleta-new-course', name: 'La Zagaleta New Course', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'marbella-club-golf', name: 'Marbella Club Golf', area: 'Costa del Sol', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'real-club-de-campo-de-malaga', name: 'Real Club de Campo de Málaga', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'alferini-golf', name: 'Alferini Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'casares-costa-golf', name: 'Casares Costa Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'el-higueral-golf', name: 'El Higueral Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'los-flamingos-golf', name: 'Los Flamingos Golf', area: 'Costa del Sol', location: 'Spain', gm_version: null, gm_confirmed: false },
  { slug: 'aguilon-golf', name: 'Aguilón Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'aldeamayor-club-de-golf', name: 'Aldeamayor Club de Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'alhama-signature', name: 'Alhama Signature', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'altea-club-de-golf', name: 'Altea Club de Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'arabella-golf-mallorca', name: 'Arabella Golf Mallorca', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'arcosur-golf', name: 'Arcosur Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'arruzafa-golf', name: 'Arruzafa Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'azata-golf', name: 'Azata Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'c.d.s.c.e.a.-barberan-and-collar', name: 'C.D.S.C.E.A. Barberán & Collar', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'c.g.b.a.-torrejon-de-ardoz', name: 'C.G.B.A. Torrejón de Ardoz', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'camposol-club-de-golf', name: 'Camposol Club de Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'club-de-campo-la-galera', name: 'Club de Campo La Galera', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'club-de-golf-aranjuez', name: 'Club de Golf Aranjuez', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'club-de-golf-barcelona', name: 'Club de Golf Barcelona', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'club-de-golf-bonalba', name: 'Club de Golf Bonalba', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'club-de-golf-entrepinos', name: 'Club de Golf Entrepinos', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'club-de-golf-hato-verde', name: 'Club de Golf Hato Verde', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'club-de-golf-navaluenga', name: 'Club de Golf Navaluenga', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'club-de-golf-pozoblanco', name: 'Club de Golf Pozoblanco', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'club-de-golf-torre-pacheco', name: 'Club de Golf Torre-Pacheco', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'club-de-golf-val-de-rois', name: 'Club de Golf Val de Rois', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'club-zaudin-golf-sevilla', name: 'Club Zaudín Golf Sevilla', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'compostela-golf', name: 'Compostela Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'desert-springs-golf-club', name: 'Desert Springs Golf Club', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'don-tello-golf', name: 'Don Tello Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'el-higueral-golf-2', name: 'El Higueral Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'el-plantio-golf-resort', name: 'El Plantío Golf Resort', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'emporda-golf-resort', name: 'Empordà Golf Resort', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'font-del-llop-golf-resort', name: 'Font del Llop Golf Resort', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'gaudi-club-de-golf', name: 'Gaudí Club de Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golf-almerimar', name: 'Golf Almerimar', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golf-ciudad-real', name: 'Golf Ciudad Real', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golf-de-andratx', name: 'Golf de Andratx', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'golf-la-dehesa-de-moron', name: 'Golf la Dehesa de Morón', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golf-los-palos', name: 'Golf Los Palos', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golf-ramon-sota', name: 'Golf Ramon Sota', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golf-ria-de-vigo', name: 'Golf Ria de Vigo', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golf-sant-marc---puigcerda', name: 'Golf Sant Marc - Puigcerdá', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golf-santander', name: 'Golf Santander', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'golf-son-gual-mallorca', name: 'Golf Son Gual Mallorca', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golf-soria', name: 'Golf Soria', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golf-valderrey', name: 'Golf Valderrey', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golfstar-cambrils', name: 'Golfstar Cambrils', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'green-paddock', name: 'Green Paddock', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'infinitum-resort', name: 'INFINITUM Resort', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'jandia-golf', name: 'Jandía Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'la-cala-golf-resort', name: 'La Cala Golf Resort', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'la-estancia-golf', name: 'La Estancia Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'la-finca-los-lagos', name: 'La Finca Los Lagos', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'la-finca-resort-and-villamartin-golf', name: 'La Finca Resort & Villamartin Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'la-loma-golf', name: 'La Loma Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'la-manga-club', name: 'La Manga Club', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'la-monacilla-golf', name: 'La Monacilla Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'la-sella-golf', name: 'La Sella Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'la-serena-golf', name: 'La Serena Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'la-valmuza-golf', name: 'La Valmuza Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'las-colinas-golf-and-country-club', name: 'Las Colinas Golf & Country Club', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'las-ramblas-golf', name: 'Las Ramblas Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'lizaso-golf-pitch-and-putt', name: 'Lizaso Golf Pitch & Putt', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'lo-romero-golf', name: 'Lo Romero Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'mino-club-de-golf-artabro', name: 'Miño Club de Golf Ártabro', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'par3-pitchandputt-gualta', name: 'Par3 Pitch&Putt Gualta', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'pitch-and-putt-sant-jordi', name: 'Pitch & Putt Sant Jordi', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'pitchandputt-palacio-urgoiti', name: 'Pitch&Putt Palacio Urgoiti', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'pretium-golf-la-junquera', name: 'Pretium Golf La Junquera', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'r.n.c.g.s.s.-basozabal', name: 'R.N.C.G.S.S. Basozabal', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'real-aero-club-de-santiago', name: 'Real Aero Club de Santiago', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'real-club-de-campo-de-cordoba', name: 'Real Club de Campo de Córdoba', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'real-club-de-golf-manises', name: 'Real Club de Golf Manises', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'real-club-sevilla-golf', name: 'Real Club Sevilla Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'real-guadalhorce-club-de-golf', name: 'Real Guadalhorce Club de Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'real-montealegre-club-de-golf', name: 'Real Montealegre Club de Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'rioja-alta-golf-club', name: 'Rioja Alta Golf Club', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'roda-golf-and-beach-resort', name: 'Roda Golf & Beach Resort', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'sancti-petri-hills-golf', name: 'Sancti Petri Hills Golf', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'senorio-de-illescas-golf-and-padel-club', name: 'Señorío de Illescas Golf & Padel Club', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'smart-golf-los-angeles-de-san-rafael', name: 'Smart Golf (Los Ángeles de San Rafael)', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'son-antem-golf-mallorca', name: 'Son Antem Golf Mallorca', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 't-golf-calvia', name: 'T-Golf Calviá', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 't-golf-palma-puntiro', name: 'T-Golf Palma Puntiró', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'tambre-golf-and-croquet', name: 'Tambre Golf & Croquet', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V3', gm_confirmed: true },
  { slug: 'valle-romano-golf-and-resort', name: 'Valle Romano Golf & Resort', area: 'Spanien övrigt', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'amendoeira-golf-resort', name: 'Amendoeira Golf Resort', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'aroeira-golf-resort', name: 'Aroeira Golf Resort', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'axis-golfe-ponte-de-lima', name: 'Axis Golfe Ponte de Lima', area: 'Portugal', location: 'Portugal', gm_version: 'V3', gm_confirmed: true },
  { slug: 'balaia-golf-village', name: 'Balaia Golf Village', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'belas-clube-de-campo', name: 'Belas Clube de Campo', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'benamor-golf', name: 'Benamor Golf', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'boavista-golf-and-spa-resort', name: 'Boavista Golf & Spa Resort', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'castro-marim-golfe-and-country-club', name: 'Castro Marim Golfe & Country Club', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'dolce-camporeal-golf-resort-and-spa', name: 'Dolce CampoReal Golf Resort & Spa', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'dom-pedro-hotels-and-golf-collection-vilamoura', name: 'Dom Pedro Hotels & Golf Collection (Vilamoura)', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'espiche-golf', name: 'Espiche Golf', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'estela-golf-club', name: 'Estela Golf Club', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'federacao-portuguesa-de-golfe-jamor', name: 'Federação Portuguesa de Golfe - Jamor', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golf-quinta-da-ria', name: 'Golf Quinta da Ria', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golfe-da-quinta-do-fojo', name: 'Golfe da Quinta do Fojo', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'guardian-bom-sucesso-golf', name: 'Guardian Bom Sucesso Golf', area: 'Portugal', location: 'Portugal', gm_version: 'V3', gm_confirmed: true },
  { slug: 'heredade-do-pinheirinho', name: 'Heredade do Pinheirinho', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'hotel-aldeia-dos-capuchos-golf-and-spa', name: 'Hotel Aldeia dos Capuchos Golf & SPA', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'life-plan-resort-ribagolfe-golf-club', name: 'Life Plan Resort Ribagolfe Golf Club', area: 'Portugal', location: 'Portugal', gm_version: 'V3', gm_confirmed: true },
  { slug: 'lisbon-sports-club', name: 'Lisbon Sports Club', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'montado-hotel-and-golf-resort', name: 'Montado Hotel & Golf Resort', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'nau-morgado-golf-and-country-club', name: 'NAU Morgado Golf & Country Club', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'ombria-golf-course', name: 'Ombria Golf Course', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'palacio-estoril-hotel-golf-and-spa', name: 'Palácio Estoril Hotel Golf & Spa', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'palheiro-golf', name: 'Palheiro Golf', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'palmares-ocean-living-and-golf-resort', name: 'Palmares Ocean Living & Golf Resort', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'pine-cliffs-resort', name: 'Pine Cliffs Resort', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'porto-santo-golfe', name: 'Porto Santo Golfe', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'praia-del-rey-golf-and-beach-resort', name: "Praia D'El Rey Golf & Beach Resort", area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'quinta-da-marinha-golf-resort', name: 'Quinta da Marinha Golf Resort', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'quinta-do-peru-golf-and-country-club', name: 'Quinta do Peru Golf & Country Club', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'quinta-do-vale-golf-resort', name: 'Quinta do Vale Golf Resort', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'royal-obidos-spa-and-golf-resort', name: 'Royal Óbidos Spa & Golf Resort', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'salgados-golf', name: 'Salgados Golf', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'santo-estevao-golfe', name: 'Santo Estevao Golfe', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'terras-da-comporta', name: 'Terras da Comporta', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'the-one-lisbon-golf', name: 'The One Lisbon Golf', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'troia-golf', name: 'Troia Golf', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'vale-do-lobo-golf', name: 'Vale do Lobo Golf', area: 'Portugal', location: 'Portugal', gm_version: 'V3', gm_confirmed: true },
  { slug: 'vale-pisao-golfe', name: 'Vale Pisão Golfe', area: 'Portugal', location: 'Portugal', gm_version: 'V3', gm_confirmed: true },
  { slug: 'vidago-palace-golf-course', name: 'Vidago Palace Golf Course', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'west-cliffs-resort', name: 'West Cliffs Resort', area: 'Portugal', location: 'Portugal', gm_version: 'V1', gm_confirmed: true },
  { slug: 'circolo-golf-venezia', name: 'Circolo Golf Venezia', area: 'Italien', location: 'Italy', gm_version: 'V1', gm_confirmed: true },
  { slug: 'garda-hotel-san-vigilio-golf-chervo', name: 'Garda Hotel San Vigilio Golf Chervò', area: 'Italien', location: 'Italy', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golf-club-colli-berici', name: 'Golf Club Colli Berici', area: 'Italien', location: 'Italy', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golf-club-jesolo', name: 'Golf Club Jesolo', area: 'Italien', location: 'Italy', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golf-club-lignano', name: 'Golf Club Lignano', area: 'Italien', location: 'Italy', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golf-del-ducato-di-parma', name: 'Golf del Ducato di Parma', area: 'Italien', location: 'Italy', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golf-salsomaggiore-terme', name: 'Golf Salsomaggiore Terme', area: 'Italien', location: 'Italy', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golf-terre-di-canossa', name: 'Golf Terre di Canossa', area: 'Italien', location: 'Italy', gm_version: 'V1', gm_confirmed: true },
  { slug: 'il-picciolo-etna-golf-resort-and-spa', name: 'Il Picciolo Etna Golf Resort & SPA', area: 'Italien', location: 'Italy', gm_version: 'V1', gm_confirmed: true },
  { slug: 'marco-simone-golf-and-country-club', name: 'Marco Simone Golf & Country Club', area: 'Italien', location: 'Italy', gm_version: 'V1', gm_confirmed: true },
  { slug: 'verdura-resort', name: 'Verdura Resort', area: 'Italien', location: 'Italy', gm_version: 'V1', gm_confirmed: true },
  { slug: 'abu-dhabi-city-golf-club', name: 'Abu Dhabi City Golf Club', area: 'Övriga marknader', location: 'UAE', gm_version: 'V1', gm_confirmed: true },
  { slug: 'al-houara-resort-and-spa', name: 'Al Houara Resort & Spa', area: 'Övriga marknader', location: 'Morocco', gm_version: 'V3', gm_confirmed: true },
  { slug: 'aphrodite-hills', name: 'Aphrodite Hills', area: 'Övriga marknader', location: 'Cyprus', gm_version: 'V3', gm_confirmed: true },
  { slug: 'buenaventura-golf-club', name: 'Buenaventura Golf Club', area: 'Övriga marknader', location: 'Panama', gm_version: 'V3', gm_confirmed: true },
  { slug: 'carden-park-golf-resort', name: 'Carden Park Golf Resort', area: 'Övriga marknader', location: 'UK', gm_version: 'V1', gm_confirmed: true },
  { slug: 'costa-navarino', name: 'Costa Navarino', area: 'Övriga marknader', location: 'Greece', gm_version: 'V1', gm_confirmed: true },
  { slug: 'elea-golf-club', name: 'Eléa Golf Club', area: 'Övriga marknader', location: 'Cyprus', gm_version: 'V3', gm_confirmed: true },
  { slug: 'estrella-del-mar-golf-and-beach-resort', name: 'Estrella Del Mar Golf & Beach Resort', area: 'Övriga marknader', location: 'Mexico', gm_version: 'V3', gm_confirmed: true },
  { slug: 'el-cortes-golf-club-puerta-cortes', name: 'El Cortés Golf Club Puerta Cortés', area: 'Övriga marknader', location: 'Mexico', gm_version: 'V3', gm_confirmed: true },
  { slug: 'flamingos-golf', name: 'Flamingos Golf', area: 'Övriga marknader', location: 'Mexico', gm_version: 'V3', gm_confirmed: true },
  { slug: 'golf-son-gual-mallorca-2', name: 'Golf Son Gual Mallorca', area: 'Övriga marknader', location: 'Spain (Mallorca)', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golf-soldeu', name: 'Golf Soldeu', area: 'Övriga marknader', location: 'Andorra', gm_version: 'V1', gm_confirmed: true },
  { slug: 'golf-waterland', name: 'Golf Waterland', area: 'Övriga marknader', location: 'Netherlands', gm_version: 'V3', gm_confirmed: true },
  { slug: 'getgolfing-org', name: 'getgolfing.org', area: 'Övriga marknader', location: 'UK', gm_version: 'V1', gm_confirmed: true },
  { slug: 'hulencourt', name: 'Hulencourt', area: 'Övriga marknader', location: 'Belgium', gm_version: 'V1', gm_confirmed: true },
  { slug: 'iberostar-bavaro-golf-club', name: 'Iberostar Bávaro Golf Club', area: 'Övriga marknader', location: 'Dominican Republic', gm_version: 'V3', gm_confirmed: true },
  { slug: 'iberostar-cancun-golf-club', name: 'Iberostar Cancún Golf Club', area: 'Övriga marknader', location: 'Mexico', gm_version: 'V3', gm_confirmed: true },
  { slug: 'iberostar-playa-paraiso-golf-club', name: 'Iberostar Playa Paraíso Golf Club', area: 'Övriga marknader', location: 'Mexico', gm_version: 'V3', gm_confirmed: true },
  { slug: 'iberostar-tierra-del-sol', name: 'Iberostar Tierra del Sol', area: 'Övriga marknader', location: 'Aruba', gm_version: 'V3', gm_confirmed: true },
  { slug: 'isabel-villas-golf-and-country-club', name: 'Isabel Villas Golf and Country Club', area: 'Övriga marknader', location: 'Dominican Republic', gm_version: 'V3', gm_confirmed: true },
  { slug: 'istanbul-golf-club-igk1895', name: 'Istanbul Golf Club IGK1895', area: 'Övriga marknader', location: 'Turkey', gm_version: 'V3', gm_confirmed: true },
  { slug: 'la-estancia-golf-resort-and-country-club', name: 'La Estancia Golf Resort & Country Club', area: 'Övriga marknader', location: 'Dominican Republic', gm_version: 'V3', gm_confirmed: true },
  { slug: 'la-romana-country-club', name: 'La Romana Country Club', area: 'Övriga marknader', location: 'Dominican Republic', gm_version: 'V3', gm_confirmed: true },
  { slug: 'limassol-greens', name: 'Limassol Greens', area: 'Övriga marknader', location: 'Cyprus', gm_version: 'V3', gm_confirmed: true },
  { slug: 'national-golf-and-country-club', name: 'National Golf & Country Club', area: 'Övriga marknader', location: 'Romania', gm_version: 'V1', gm_confirmed: true },
  { slug: 'oakwood-resort', name: 'Oakwood Resort', area: 'Övriga marknader', location: 'Canada', gm_version: 'V3', gm_confirmed: true },
  { slug: 'onward-mangilao-golf-club-guam', name: 'Onward Mangilao Golf Club Guam', area: 'Övriga marknader', location: 'USA', gm_version: 'V1', gm_confirmed: true },
  { slug: 'oustoen-country-club', name: 'Oustøen Country Club', area: 'Övriga marknader', location: 'Norway', gm_version: 'V1', gm_confirmed: true },
  { slug: 'puerto-aventuras-golf-and-racquet-club', name: 'Puerto Aventuras Golf & Racquet Club', area: 'Övriga marknader', location: 'Mexico', gm_version: 'V3', gm_confirmed: true },
  { slug: 'pun-hlaing-golf-club', name: 'Pun Hlaing Golf Club', area: 'Övriga marknader', location: 'Myanmar', gm_version: 'V1', gm_confirmed: true },
  { slug: 'real-del-mar-golf-and-country-club', name: 'Real Del Mar Golf & Country Club', area: 'Övriga marknader', location: 'Mexico', gm_version: 'V3', gm_confirmed: true },
  { slug: 'santo-domingo-country-club', name: 'Santo Domingo Country Club', area: 'Övriga marknader', location: 'Dominican Republic', gm_version: 'V1', gm_confirmed: true },
  { slug: 'stonehill-golf-club', name: 'Stonehill Golf Club', area: 'Övriga marknader', location: 'Thailand', gm_version: 'V1', gm_confirmed: true },
  { slug: 'the-royal-golf-club-bahrain', name: 'The Royal Golf Club Bahrain', area: 'Övriga marknader', location: 'Bahrain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'the-san-roque-club', name: 'The San Roque Club', area: 'Övriga marknader', location: 'Spain', gm_version: 'V1', gm_confirmed: true },
  { slug: 'the-springs-campestre-club', name: 'The Springs Campestre Club', area: 'Övriga marknader', location: 'Mexico', gm_version: 'V3', gm_confirmed: true },
  { slug: 'tpc-danzante-bay', name: 'TPC Danzante Bay', area: 'Övriga marknader', location: 'Mexico', gm_version: 'V1', gm_confirmed: true },
  { slug: 'vistacana-golf-club', name: 'Vistacana Golf Club', area: 'Övriga marknader', location: 'Dominican Republic', gm_version: 'V3', gm_confirmed: true },
  { slug: 'vistas-golf-country-club', name: 'Vistas Golf Country Club', area: 'Övriga marknader', location: 'Dominican Republic', gm_version: 'V1', gm_confirmed: true },
  { slug: 'welbeck-manor-and-golf', name: 'Welbeck Manor & Golf', area: 'Övriga marknader', location: 'UK', gm_version: 'V3', gm_confirmed: true },
  { slug: 'windsor-golf-hotel-and-country-club', name: 'Windsor Golf Hotel & Country Club', area: 'Övriga marknader', location: 'Kenya', gm_version: 'V3', gm_confirmed: true },
];

async function seed() {
  console.log(`\n🌱 Seeder startar – ${ALL_CLUBS.length} klubbar att importera...\n`);

  const rows = ALL_CLUBS.map((c, i) => ({
    slug: c.slug,
    name: c.name,
    area: c.area,
    location: c.location,
    gm_version: c.gm_version,
    active: false,
    has_last_minute: false,
    rating: 0,
    reviews: 0,
    holes: 18,
    par: 72,
    difficulty: 'medium',
    from_price: 0,
    image: '',
    lat: 0,
    lng: 0,
    sort_order: i + 1,
  }));

  // Upsert i batchar om 50 för att undvika timeouts
  const BATCH = 50;
  let inserted = 0;
  let skipped = 0;

  for (let i = 0; i < rows.length; i += BATCH) {
    const batch = rows.slice(i, i + BATCH);
    const { data, error } = await supabase
      .from('courses')
      .upsert(batch, { onConflict: 'slug', ignoreDuplicates: true })
      .select('slug');

    if (error) {
      console.error(`❌ Batch ${i / BATCH + 1} fel:`, error.message);
    } else {
      inserted += data?.length ?? 0;
      skipped += batch.length - (data?.length ?? 0);
      console.log(`✅ Batch ${i / BATCH + 1}: ${data?.length ?? 0} insatta, ${batch.length - (data?.length ?? 0)} hoppades över`);
    }
  }

  console.log(`\n🎉 Klar! ${inserted} insatta, ${skipped} redan existerande.\n`);
}

seed().catch(err => {
  console.error('❌ Seed misslyckades:', err.message);
  process.exit(1);
});
